#ifndef CONSTANTESJUGADOR_H
#define CONSTANTESJUGADOR_H

const int CANTIDAD_OBJETIVOS = 3;
const int CANTIDAD_MINIMA_ENERGIA = 0;
const int CANTIDAD_MAXIMA_ENERGIA = 100;
/*
enum objetivos_t {
    COMPRAR_ANDYPOLIS = 1,
    EDAD_DE_PIEDRA = 2,
    BOMBARDERO = 3,
    ENERGETICO = 4,
    LETRADO = 5,
    MINERO = 6,
    CANSADO = 7, 
    CONSTRUCTOR = 8,
    ARMADO = 9,
    EXTREMIDA = 10
};
*/
#endif